package dev.smpeconomy.message;

import java.util.Set;

/** Messages owned by the economy itself: shop, sell, worth, player shop, market. */
public enum CoreKeys implements MessageKey {

    PREFIX("prefix"),
    PLAYERS_ONLY("general.players-only"),
    PLAYERSHOP_SELL_HOLD_ITEM("playershop.sell.hold-item"),
    PLAYERSHOP_SELL_CREATED("playershop.sell.created", "item", "price", "quantity"),
    PLAYERSHOP_SELL_NOT_ENOUGH("playershop.sell.not-enough-items"),
    PLAYERSHOP_SELL_MAX_LISTINGS("playershop.sell.max-listings"),
    PLAYERSHOP_SELL_MAX_LISTINGS_CAPPED("playershop.sell.max-listings-capped", "cap"),
    PLAYERSHOP_SELL_PRICE_TOO_LOW("playershop.sell.price-too-low", "minimum"),
    PLAYERSHOP_SELL_FAILED("playershop.sell.failed"),
    PLAYERSHOP_LIST_EMPTY("playershop.list.empty"),
    PLAYERSHOP_LIST_HEADER("playershop.list.header"),
    PLAYERSHOP_LIST_ENTRY("playershop.list.entry", "item", "price", "quantity", "sold"),
    PLAYERSHOP_LIST_ENTRY_SOLD("playershop.list.entry-sold-suffix", "quantity"),
    WORTH_UNKNOWN_ITEM("worth.unknown-item", "item"),
    WORTH_HOLD_ITEM("worth.hold-item"),
    WORTH_NO_VALUE("worth.no-sell-value", "item"),
    WORTH_HEADER("worth.header", "category", "item"),
    WORTH_UNIT_EFFECTIVE("worth.unit-price-effective", "price"),
    WORTH_UNIT_BASE("worth.unit-price-base", "price"),
    WORTH_STACK("worth.stack-total", "quantity", "total"),
    SHOP_CATEGORY_TITLE("shop.category.title", "category"),
    SHOP_CATEGORY_QTY_PER_CLICK("shop.category.qty-per-click", "quantity"),
    SHOP_CATEGORY_PRICE("shop.category.price", "price", "trend"),
    SHOP_CATEGORY_TREND_UP("shop.category.trend-up", "trend"),
    SHOP_CATEGORY_TREND_DOWN("shop.category.trend-down", "trend"),
    SHOP_CATEGORY_LEFT_CLICK("shop.category.left-click", "quantity"),
    SHOP_CATEGORY_RIGHT_CLICK("shop.category.right-click", "quantity"),
    SHOP_CATEGORY_SHIFT_CLICK("shop.category.shift-click", "quantity"),
    SELL_GUI_TITLE("sell.gui.title"),
    WORTHS_TITLE("worths.title"),
    WORTHS_PRICE_LINE("worths.price-line", "price", "trend"),
    WORTHS_TREND_UP("worths.trend-up", "percent"),
    WORTHS_TREND_DOWN("worths.trend-down", "percent"),
    WORTHS_TREND_FLAT("worths.trend-flat"),
    WORTHS_FILTER_TITLE("worths.filter.title"),
    WORTHS_FILTER_OPTION_ACTIVE("worths.filter.option-active", "label"),
    WORTHS_FILTER_OPTION_INACTIVE("worths.filter.option-inactive", "label"),
    PLAYERSHOP_FILTER_TITLE("playershop.filter.title"),
    PLAYERSHOP_FILTER_OPTION_ACTIVE("playershop.filter.option-active", "label"),
    PLAYERSHOP_FILTER_OPTION_INACTIVE("playershop.filter.option-inactive", "label"),
    PLAYERSHOP_FILTER_DESCRIPTION("playershop.filter.description", "description"),
    PLAYERSHOP_FILTER_CURRENTLY_ACTIVE("playershop.filter.currently-active"),
    PLAYERSHOP_FILTER_CLICK_TO_APPLY("playershop.filter.click-to-apply"),
    PLAYERSHOP_FILTER_BACK("playershop.filter.back"),
    MULTI_MAIN_TITLE("multi.main.title"),
    MULTI_MAIN_CATEGORY("multi.main.category", "category"),
    MULTI_MAIN_LEVEL("multi.main.level", "level"),
    MULTI_MAIN_MULTIPLIER("multi.main.multiplier", "multiplier"),
    MULTI_MAIN_PROGRESS("multi.main.progress", "progress"),
    MULTI_MAIN_CLICK_DETAILS("multi.main.click-for-details"),
    PLAYERSHOP_STORAGE_TITLE("playershop.storage.title"),
    PLAYERSHOP_STORAGE_ALL_CLAIMED("playershop.storage.all-claimed"),
    PLAYERSHOP_STORAGE_CLICK_TO_CLAIM("playershop.storage.click-to-claim"),
    PLAYERSHOP_STORAGE_CLAIM_ALL("playershop.storage.claim-all"),
    PLAYERSHOP_STORAGE_CLAIM_ALL_LORE("playershop.storage.claim-all-lore"),
    SHOP_MAIN_TITLE("shop.main.title"),
    SHOP_MAIN_BALANCE("shop.main.balance", "balance"),
    SHOP_MAIN_ICON_SERVER_SHOP("shop.main.icon-server-shop"),
    SHOP_MAIN_ICON_TOP_ITEMS("shop.main.icon-top-items"),
    SHOP_MAIN_ICON_HISTORY("shop.main.icon-history"),
    SHOP_MAIN_ICON_PLAYER_SHOP("shop.main.icon-player-shop"),
    SHOP_MAIN_TOP_ITEMS_LORE("shop.main.top-items-lore"),
    SHOP_MAIN_HISTORY_LORE("shop.main.history-lore"),
    SHOP_MAIN_PLAYER_SHOP_LORE("shop.main.player-shop-lore"),
    SHOP_MAIN_SECTION_ITEM_COUNT("shop.main.section-item-count", Plural.on("count")),
    SHOP_MAIN_CLICK_TO_OPEN("shop.main.click-to-open"),
    SHOP_MAIN_CLICK_TO_BROWSE("shop.main.click-to-browse"),
    PLAYERSHOP_HISTORY_TITLE("playershop.history.title"),
    PLAYERSHOP_HISTORY_ENTRY_NAME("playershop.history.entry-name", "item"),
    PLAYERSHOP_HISTORY_QTY("playershop.history.qty", "quantity"),
    PLAYERSHOP_HISTORY_PRICE("playershop.history.price", "price"),
    PLAYERSHOP_HISTORY_TOTAL_SPENT("playershop.history.total-spent", "total"),
    PLAYERSHOP_HISTORY_TOTAL_EARNED("playershop.history.total-earned", "total"),
    PLAYERSHOP_HISTORY_WHEN("playershop.history.when", "when"),
    PLAYERSHOP_HISTORY_TOGGLE_PURCHASES("playershop.history.toggle-purchases"),
    PLAYERSHOP_HISTORY_TOGGLE_SALES("playershop.history.toggle-sales"),
    PLAYERSHOP_HISTORY_PURCHASES_LORE("playershop.history.purchases-lore"),
    PLAYERSHOP_HISTORY_SALES_LORE("playershop.history.sales-lore"),
    PLAYERSHOP_HISTORY_SWITCH_TO_SALES("playershop.history.switch-to-sales"),
    PLAYERSHOP_HISTORY_SWITCH_TO_PURCHASES("playershop.history.switch-to-purchases"),
    PLAYERSHOP_HISTORY_TOGGLE_SERVER_SHOP("playershop.history.toggle-server-shop"),
    PLAYERSHOP_HISTORY_TOGGLE_PLAYER_SHOP("playershop.history.toggle-player-shop"),
    PLAYERSHOP_HISTORY_SERVER_SHOP_LORE("playershop.history.server-shop-lore"),
    PLAYERSHOP_HISTORY_PLAYER_SHOP_LORE("playershop.history.player-shop-lore"),
    PLAYERSHOP_HISTORY_SWITCH_TO_PLAYER_SHOP("playershop.history.switch-to-player-shop"),
    PLAYERSHOP_HISTORY_SWITCH_TO_SERVER_SHOP("playershop.history.switch-to-server-shop"),
    PLAYERSHOP_HISTORY_EMPTY("playershop.history.empty"),
    MULTI_CATEGORY_TITLE("multi.category.title", "category"),
    MULTI_CATEGORY_MULT_COMPLETE("multi.category.multiplier-complete", "multiplier"),
    MULTI_CATEGORY_MULT_CURRENT("multi.category.multiplier-current", "multiplier"),
    MULTI_CATEGORY_MULT_LOCKED("multi.category.multiplier-locked", "multiplier"),
    MULTI_CATEGORY_COMPLETE("multi.category.complete"),
    MULTI_CATEGORY_PROGRESS("multi.category.progress", "current", "percent", "total"),
    MULTI_CATEGORY_LOCKED("multi.category.locked"),
    MULTI_CATEGORY_STAGE_COMPLETE("multi.category.stage-complete", "stage"),
    MULTI_CATEGORY_STAGE_CURRENT("multi.category.stage-current", "stage"),
    MULTI_CATEGORY_STAGE_LOCKED("multi.category.stage-locked", "stage"),
    MULTI_CATEGORY_ICON_NAME("multi.category.icon-name", "category"),
    MULTI_CATEGORY_CURRENT_MULT_MAX("multi.category.current-multiplier-max", "multiplier"),
    MULTI_CATEGORY_CURRENT_MULT("multi.category.current-multiplier", "multiplier"),
    MULTI_CATEGORY_LEVEL("multi.category.level", "level", "max"),
    MULTI_CATEGORY_BACK("multi.category.back"),
    SHOP_BUY_TITLE("shop.buy.title", "item"),
    SHOP_BUY_DECREASE("shop.buy.decrease", "amount"),
    SHOP_BUY_INCREASE("shop.buy.increase", "amount"),
    SHOP_BUY_CANCEL("shop.buy.cancel"),
    SHOP_BUY_CONFIRM("shop.buy.confirm"),
    SHOP_BUY_ITEM_NAME("shop.buy.item-name", "item"),
    SHOP_BUY_QUANTITY("shop.buy.quantity", "quantity"),
    SHOP_BUY_UNIT_PRICE("shop.buy.unit-price", "price"),
    SHOP_BUY_TOTAL_AFFORDABLE("shop.buy.total-affordable", "total"),
    SHOP_BUY_TOTAL_UNAFFORDABLE("shop.buy.total-unaffordable", "total"),
    SHOP_BUY_BALANCE("shop.buy.balance", "balance"),
    SHOP_BUY_CLICK_TO_CONFIRM("shop.buy.click-to-confirm"),
    SHOP_BUY_PURCHASED("shop.buy.purchased", "cost", "item", "quantity"),
    SHOP_BUY_PURCHASED_PARTIAL("shop.buy.purchased-partial", "cost", "item", "quantity"),
    SHOP_BUY_CANNOT_AFFORD("shop.buy.cannot-afford"),
    SHOP_BUY_INVENTORY_FULL("shop.buy.inventory-full"),
    MARKET_STATS_TITLE("market-stats.title"),
    MARKET_STATS_CONTROLS_NAME("market-stats.controls-name"),
    MARKET_STATS_PERIOD("market-stats.period", "period"),
    MARKET_STATS_METRIC("market-stats.metric", "metric"),
    MARKET_STATS_SORT_BY("market-stats.sort-by", "sort"),
    MARKET_STATS_HINT_METRIC("market-stats.hint-metric"),
    MARKET_STATS_HINT_PERIOD("market-stats.hint-period"),
    MARKET_STATS_HINT_SORT("market-stats.hint-sort"),
    MARKET_STATS_SCOPE_NAME("market-stats.scope-name", "scope"),
    MARKET_STATS_SCOPE_LORE("market-stats.scope-lore"),
    MARKET_STATS_SCOPE_CYCLE("market-stats.scope-cycle"),
    MARKET_STATS_ENTRY_RANK_1("market-stats.entry-rank-1", "item"),
    MARKET_STATS_ENTRY_RANK_2("market-stats.entry-rank-2", "item"),
    MARKET_STATS_ENTRY_RANK_3("market-stats.entry-rank-3", "item"),
    MARKET_STATS_ENTRY_RANK_OTHER("market-stats.entry-rank-other", "item", "rank"),
    MARKET_STATS_VOLUME("market-stats.volume", Plural.on("quantity")),
    MARKET_STATS_VALUE("market-stats.value", "value"),
    MARKET_STATS_EMPTY("market-stats.empty"),
    PLAYERSHOP_MENU_TITLE("playershop.menu.title"),
    PLAYERSHOP_MENU_OWN_LISTING("playershop.menu.own-listing"),
    PLAYERSHOP_MENU_OUT_OF_STOCK("playershop.menu.out-of-stock"),
    PLAYERSHOP_MENU_NOTHING_TO_SELL("playershop.menu.nothing-to-sell"),
    PLAYERSHOP_MENU_QUANTITY_BUY_TITLE("playershop.menu.quantity-buy-title", "item"),
    PLAYERSHOP_MENU_QUANTITY_SELL_TITLE("playershop.menu.quantity-sell-title", "item"),
    PLAYERSHOP_MENU_PURCHASED("playershop.menu.purchased", "item", "quantity", "total"),
    PLAYERSHOP_MENU_SOLD("playershop.menu.sold", "item", "quantity", "total"),
    PLAYERSHOP_MENU_CANNOT_AFFORD("playershop.menu.cannot-afford"),
    PLAYERSHOP_MENU_NOT_ENOUGH_ITEMS("playershop.menu.not-enough-items"),
    PLAYERSHOP_MENU_UNAVAILABLE("playershop.menu.unavailable"),
    PLAYERSHOP_MENU_FAILED("playershop.menu.failed", "reason"),
    PLAYERSHOP_MENU_ITEM_NAME("playershop.menu.item-name", "item"),
    PLAYERSHOP_MENU_SELLER("playershop.menu.seller", "seller"),
    PLAYERSHOP_MENU_PRICE("playershop.menu.price", "price"),
    PLAYERSHOP_MENU_FILLED("playershop.menu.filled", "filled", "total"),
    PLAYERSHOP_MENU_AVAILABLE("playershop.menu.available", "available"),
    PLAYERSHOP_MENU_EXPIRES("playershop.menu.expires", "time"),
    PLAYERSHOP_MENU_CLICK_TO_BUY("playershop.menu.click-to-buy"),
    PLAYERSHOP_MENU_CLICK_TO_FULFILL("playershop.menu.click-to-fulfill"),
    PLAYERSHOP_MENU_TOGGLE_SELL("playershop.menu.toggle-sell"),
    PLAYERSHOP_MENU_TOGGLE_BUY("playershop.menu.toggle-buy"),
    PLAYERSHOP_MENU_TOGGLE_SELL_LORE("playershop.menu.toggle-sell-lore"),
    PLAYERSHOP_MENU_TOGGLE_BUY_LORE("playershop.menu.toggle-buy-lore"),
    PLAYERSHOP_MENU_CLICK_TO_SWITCH("playershop.menu.click-to-switch"),
    PLAYERSHOP_MENU_FILTER("playershop.menu.filter"),
    PLAYERSHOP_MENU_FILTER_ACTIVE("playershop.menu.filter-active", "sort"),
    PLAYERSHOP_MENU_FILTER_CLICK("playershop.menu.filter-click"),
    PLAYERSHOP_MENU_MY_OFFERS("playershop.menu.my-offers"),
    PLAYERSHOP_MENU_MY_OFFERS_LORE("playershop.menu.my-offers-lore"),
    PLAYERSHOP_MENU_NEW_OFFER("playershop.menu.new-offer"),
    PLAYERSHOP_MENU_NEW_OFFER_LORE("playershop.menu.new-offer-lore"),
    PLAYERSHOP_OFFERS_TITLE("playershop.offers.title"),
    PLAYERSHOP_OFFERS_CLAIMED("playershop.offers.claimed"),
    PLAYERSHOP_OFFERS_ITEM_NAME("playershop.offers.item-name", "item"),
    PLAYERSHOP_OFFERS_TYPE_SELL("playershop.offers.type-sell"),
    PLAYERSHOP_OFFERS_TYPE_BUY("playershop.offers.type-buy"),
    PLAYERSHOP_OFFERS_PRICE("playershop.offers.price", "price"),
    PLAYERSHOP_OFFERS_FILLED("playershop.offers.filled", "filled", "total"),
    PLAYERSHOP_OFFERS_EXPIRES("playershop.offers.expires", "time"),
    PLAYERSHOP_OFFERS_CLICK_CANCEL("playershop.offers.click-cancel"),
    PLAYERSHOP_OFFERS_DONE_NAME("playershop.offers.done-name", "item"),
    PLAYERSHOP_OFFERS_ORDER_FILLED("playershop.offers.order-filled"),
    PLAYERSHOP_OFFERS_LISTING_CLOSED("playershop.offers.listing-closed"),
    PLAYERSHOP_OFFERS_CLICK_CLAIM("playershop.offers.click-claim"),
    PLAYERSHOP_OFFERS_TOGGLE_SELL("playershop.offers.toggle-sell"),
    PLAYERSHOP_OFFERS_TOGGLE_BUY("playershop.offers.toggle-buy"),
    PLAYERSHOP_OFFERS_SHOWING_SELL("playershop.offers.showing-sell"),
    PLAYERSHOP_OFFERS_SHOWING_BUY("playershop.offers.showing-buy"),
    PLAYERSHOP_OFFERS_CLICK_SWITCH("playershop.offers.click-switch"),
    PLAYERSHOP_OFFERS_ALL("playershop.offers.all"),
    PLAYERSHOP_OFFERS_ALL_LORE("playershop.offers.all-lore"),
    PLAYERSHOP_OFFERS_CLAIM_ITEMS("playershop.offers.claim-items"),
    PLAYERSHOP_OFFERS_CLAIM_ITEMS_LORE("playershop.offers.claim-items-lore"),
    PLAYERSHOP_OFFERS_NEW("playershop.offers.new"),
    PLAYERSHOP_OFFERS_NEW_LORE("playershop.offers.new-lore"),
    PLAYERSHOP_NEW_TITLE("playershop.new.title"),
    PLAYERSHOP_NEW_PLACE_ITEM_FIRST("playershop.new.place-item-first"),
    PLAYERSHOP_NEW_SEARCH_FIRST("playershop.new.search-first"),
    PLAYERSHOP_NEW_PROMPT("playershop.new.chat-prompt"),
    PLAYERSHOP_NEW_UNKNOWN_ITEM("playershop.new.unknown-item", "input"),
    PLAYERSHOP_NEW_NONE_IN_INVENTORY("playershop.new.none-in-inventory", "item"),
    PLAYERSHOP_NEW_QTY_BUY_TITLE("playershop.new.quantity-buy-title", "item"),
    PLAYERSHOP_NEW_QTY_SELL_TITLE("playershop.new.quantity-sell-title", "item"),
    PLAYERSHOP_NEW_INVALID_PRICE("playershop.new.invalid-price"),
    PLAYERSHOP_NEW_PRICE_POSITIVE("playershop.new.price-must-be-positive"),
    PLAYERSHOP_NEW_BUY_CREATED("playershop.new.buy-order-created", "item", "price", "quantity"),
    PLAYERSHOP_NEW_SELL_CREATED("playershop.new.sell-listing-created", "item", "price", "quantity"),
    PLAYERSHOP_NEW_NO_ESCROW("playershop.new.cannot-afford-escrow"),
    PLAYERSHOP_NEW_NOT_ENOUGH("playershop.new.not-enough-items"),
    PLAYERSHOP_NEW_MAX_LISTINGS("playershop.new.max-listings"),
    PLAYERSHOP_NEW_MAX_LISTINGS_CAPPED("playershop.new.max-listings-capped", "cap"),
    PLAYERSHOP_NEW_PRICE_TOO_LOW("playershop.new.price-too-low", "minimum"),
    PLAYERSHOP_NEW_PRICE_TOO_HIGH("playershop.new.price-too-high", "maximum"),
    PLAYERSHOP_NEW_FAILED("playershop.new.failed"),
    PLAYERSHOP_NEW_SEARCH_NAME("playershop.new.search-name"),
    PLAYERSHOP_NEW_SEARCH_LORE_1("playershop.new.search-lore-1"),
    PLAYERSHOP_NEW_SEARCH_LORE_2("playershop.new.search-lore-2"),
    PLAYERSHOP_NEW_SEARCH_LORE_3("playershop.new.search-lore-3"),
    PLAYERSHOP_NEW_SEARCH_LORE_4("playershop.new.search-lore-4"),
    PLAYERSHOP_NEW_NO_ITEM("playershop.new.no-item"),
    PLAYERSHOP_NEW_NO_ITEM_LORE_1("playershop.new.no-item-lore-1"),
    PLAYERSHOP_NEW_NO_ITEM_LORE_2("playershop.new.no-item-lore-2"),
    PLAYERSHOP_NEW_SELECTED_NAME("playershop.new.selected-name", "item"),
    PLAYERSHOP_NEW_SELECTED_LORE_1("playershop.new.selected-lore-1"),
    PLAYERSHOP_NEW_SELECTED_LORE_2("playershop.new.selected-lore-2"),
    PLAYERSHOP_NEW_SELL_BUTTON("playershop.new.sell-button"),
    PLAYERSHOP_NEW_SELL_LORE_1("playershop.new.sell-lore-1"),
    PLAYERSHOP_NEW_SELL_LORE_2("playershop.new.sell-lore-2"),
    PLAYERSHOP_NEW_BUY_BUTTON("playershop.new.buy-button"),
    PLAYERSHOP_NEW_BUY_LORE_1("playershop.new.buy-lore-1"),
    PLAYERSHOP_NEW_BUY_LORE_2("playershop.new.buy-lore-2"),
    PLAYERSHOP_NEW_CANCEL("playershop.new.cancel"),
    SELL_EARNINGS_ACTIONBAR("sell.earnings-actionbar", "amount"),
    SELL_LEVEL_UP("sell.level-up", "category", "level", "multiplier");

    private final String path;
    private final Set<String> tokens;

    CoreKeys(String path, String... tokens) {
        this.path = path;
        this.tokens = Set.of(tokens);
        this.plural = false;
        this.countToken = null;
    }

    @Override
    public String path() {
        return path;
    }

    @Override
    public Set<String> declaredTokens() {
        return tokens;
    }

    private final boolean plural;
    private final String countToken;

    CoreKeys(String path, Plural plural) {
        this.path = path;
        this.tokens = plural.tokens();
        this.plural = true;
        this.countToken = plural.countToken();
    }

    @Override
    public boolean plural() {
        return plural;
    }

    @Override
    public String countToken() {
        return countToken;
    }
}
